/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fcf9f8",
        "on-surface-variant": "#4b4452",
        "on-primary-fixed-variant": "#6122a0",
        "secondary-fixed": "#f0dbff",
        "secondary-fixed-dim": "#ddb7ff",
        "outline": "#7d7483",
        "surface-tint": "#7a3fba",
        "tertiary": "#371700",
        "surface-container": "#f0edec",
        "inverse-primary": "#dbb8ff",
        "surface-bright": "#fcf9f8",
        "inverse-surface": "#313030",
        "primary-fixed": "#efdbff",
        "background": "#fcf9f8",
        "on-error": "#ffffff",
        "on-secondary-container": "#fffbff",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-container": "#bd82ff",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ebe7e7",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#6d390f",
        "surface-variant": "#e5e2e1",
        "on-secondary-fixed-variant": "#6900b3",
        "on-primary": "#ffffff",
        "primary": "#31005d",
        "on-secondary-fixed": "#2c0050",
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3f2",
        "surface-container-highest": "#e5e2e1",
        "on-tertiary-fixed": "#311300",
        "on-tertiary-container": "#d48e5d",
        "secondary-container": "#9e42f2",
        "primary-container": "#4e008e",
        "primary-fixed-dim": "#dbb8ff",
        "on-secondary": "#ffffff",
        "surface-dim": "#dcd9d9",
        "outline-variant": "#cec3d4",
        "on-surface": "#1c1b1b",
        "secondary": "#841cd8",
        "tertiary-container": "#572800",
        "tertiary-fixed": "#ffdcc6",
        "on-background": "#1c1b1b",
        "tertiary-fixed-dim": "#ffb786",
        "on-primary-fixed": "#2b0052"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "md": "24px",
        "margin-mobile": "16px",
        "sm": "12px",
        "gutter": "20px",
        "xs": "4px",
        "xl": "64px",
        "lg": "40px",
        "base": "8px"
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "caption": ["Inter"],
        "label-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm-mobile": ["Inter"]
      },
      fontSize: {
        "headline-sm": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "caption": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-sm-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
